Run a code cell using "Shift" + "Enter" keys or pressing the button "Cell" -> "Run Cells" in Jupyter Notebook.

In [1]:
print("Hello")

Hello


In [2]:
print("2+3 = ", 2+5 )
print("2*3 = ", 2*5 )
print("2/3 = ", 2/5 )
print("2**3 = ", 2**5)
print("2%3 = ", 2%5)
print("2//3 = ", 2//5)

2+3 =  7
2*3 =  10
2/3 =  0.4
2**3 =  32
2%3 =  2
2//3 =  0


In [3]:
a = 3
print(a)

a = a + 2
print(a)

a += 5
print(a)

a *= 2
print(a)

3
5
10
20


In [4]:
a = [1,2,3,4,5,6,7]
print(a)
print(a[0])
print(a[1:3])
print(a[0:2]+a[4:6])

b = len(a)
print(b)

[1, 2, 3, 4, 5, 6, 7]
1
[2, 3]
[1, 2, 5, 6]
7


In [5]:
import numpy as np

a = np.pi
print(a)

b = np.sqrt(9)
print(b)

3.141592653589793
3.0


In [6]:
import numpy as np

a = np.ones(5)
print(a)

b = np.ones((2,3))
print(b)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
import numpy as np

a = np.zeros(5)
print(a)

b = np.arange(5)
print(b)

[0. 0. 0. 0. 0.]
[0 1 2 3 4]


In [8]:
import numpy as np

a = np.arange(4,12)
print(a)

b = np.arange(4,12,2)
print(b)

c = np.arange(4,12,4)
print(c)

d = np.linspace(4, 12, 2)
print(d)

e = np.linspace(4, 12, 4)
print(e)

[ 4  5  6  7  8  9 10 11]
[ 4  6  8 10]
[4 8]
[ 4. 12.]
[ 4.          6.66666667  9.33333333 12.        ]


In [9]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a+2)
print(a*2)
print(a/2)

[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [10]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)

b = a.T
print(b)

c = a.reshape(3, 2)
print(c)

d = a.flatten()
print(d)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [11]:
import numpy as np

a = [1,2,3,4,5]
print(a)

b = np.sum(a)
print(b)


[1, 2, 3, 4, 5]
15


In [12]:
for x in range(5):
    print("Loop", x)

Loop 0
Loop 1
Loop 2
Loop 3
Loop 4


In [13]:
for x in ["red", "green", "blue"]:
    print(x)

red
green
blue


In [14]:
print("3==3: ", 3==3)
print("3!=1: ", 3!=1)
print("1==3: ", 1==3)
print("1!=3: ", 1!=3)
print("1<3: ", 1<3)
print("3<3: ", 3<3)
print("3<=3: ", 3<=3)
print("1>3: ", 1>3)

3==3:  True
3!=1:  True
1==3:  False
1!=3:  True
1<3:  True
3<3:  False
3<=3:  True
1>3:  False


In [15]:
a = 3
print("a = " a)

if a == 3:
    print("(if) 2a = ", 2*a)
else:
    print("(else) 3a = ", 3*a)

a =  3


In [16]:
a = 5
print("a = " a)

if a == 3:
    print("(if) 2a = ", 2*a)
elif a > 3:
    print("(elif) 3a = ", 3*a)
else:
    print("(else) 4a = ", 4*a)

a =  5
