This is an essential guide to learn a python programming with basic exercises.
You can run a code cell using "Shift" + "Enter" keys or pressing the button "Cell" -> "Run Cells" in Jupyter Notebook (https://jupyter.org/).

In [1]:
print("Hello")

Hello


-------------------------------
Python Arithmetic Operators

In [2]:
print("2+5  = ", 2+5 )
print("2*5  = ", 2*5 )
print("2/5  = ", 2/5 )
print("2**5 = ", 2**5)
print("2%5  = ", 2%5)
print("2//5 = ", 2//5)

2+3  =  7
2*3  =  10
2/3  =  0.4
2**3 =  32
2%3  =  2
2//3 =  0


-----------------------------
Python Assignment Operators

In [3]:
a = 3
print("a = ", a)

a = a + 2
print("a = ", a)

a += 5
print("a = ", a)

a *= 2
print("a = ", a)

a =  3
a =  5
a =  10
a =  20


----------------
Python Array

In [4]:
a = [1,2,3,4,5,6,7]
print("a    = ", a)
print("a[0] = ", a[0])
print("a[1:3] = ", a[1:3])
print("a[0:2]+a[4:6] = ", a[0:2]+a[4:6])

b = len(a)
print("b    = ", b)

a    =  [1, 2, 3, 4, 5, 6, 7]
a[0] =  1
a[1:3] =  [2, 3]
a[0:2]+a[4:6] =  [1, 2, 5, 6]
b    =  7


--------------
NumPy (https://numpy.org/) is a package for scientific computing, and it offers comprehensive mathematical functions.

In [5]:
a = [1,2,3,4]
print("a   = ",  a)
print("a*2 = ", a*2)

import numpy as np

b = np.array( [1,2,3,4] )
print("b   = ", b)
print("b*2 = ", b*2)

a   =  [1, 2, 3, 4]
a*2 =  [1, 2, 3, 4, 1, 2, 3, 4]
b   =  [1 2 3 4]
b*2 =  [2 4 6 8]


In [6]:
import numpy as np

a = np.array( [1,2,3,4,5] )
print("a+2 = ", a+2)
print("a*2 = ", a*2)
print("a/2 = ", a/2)

a+2 =  [3 4 5 6 7]
a*2 =  [ 2  4  6  8 10]
a/2 =  [0.5 1.  1.5 2.  2.5]


In [7]:
import numpy as np

a = np.ones(5)
print("a = ", a)

b = np.ones((2,3))
print("b = \n", b)

a =  [1. 1. 1. 1. 1.]
b = 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
import numpy as np

a = np.zeros(5)
print("a = ", a)

b = np.arange(5)
print("b = ", b)

a =  [0. 0. 0. 0. 0.]
b =  [0 1 2 3 4]


In [9]:
import numpy as np

a = np.arange(12)
print("a = ", a)

b = np.arange(4,12)
print("b = ", b)

c = np.arange(4,12,2)
print("c = ", c)

d = np.arange(4,12,3)
print("d = ", d)

e = np.linspace(4, 12, 2)
print("e = ", e)

f = np.linspace(4, 12, 3)
print("f = ", f)

a =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
b =  [ 4  5  6  7  8  9 10 11]
c =  [ 4  6  8 10]
d =  [ 4  7 10]
e =  [ 4. 12.]
f =  [ 4.  8. 12.]


In [10]:
import numpy as np

a = np.array( [[1,2,3],[4,5,6]] )
print("a = \n", a)

b = a.T
print("b = \n", b)

c = a.reshape(3, 2)
print("c = \n", c)

d = a.flatten()
print("d = \n", d)

a = 
 [[1 2 3]
 [4 5 6]]
b = 
 [[1 4]
 [2 5]
 [3 6]]
c = 
 [[1 2]
 [3 4]
 [5 6]]
d = 
 [1 2 3 4 5 6]


In [11]:
import numpy as np

a = [1,2,3,4,5]
print("a = ", a)

b = np.sum(a)
print("b = ", b)

a =  [1, 2, 3, 4, 5]
b =  15


In [12]:
import numpy as np

a = np.pi
print("a = ", a)

b = np.sqrt(9)
print("b = ", b)

a =  3.141592653589793
b =  3.0


----------------------
Python For Loops 

In [13]:
for x in range(5):
    print("Loop", x)

Loop 0
Loop 1
Loop 2
Loop 3
Loop 4


In [14]:
for x in ["red", "green", "blue"]:
    print(x)

red
green
blue


-----------------------------
* Python Comparison Operators

In [15]:
print("3==3: ", 3==3)
print("3!=1: ", 3!=1)
print("1==3: ", 1==3)
print("1!=3: ", 1!=3)
print("1<3 : ", 1<3)
print("3<3 : ", 3<3)
print("3<=3: ", 3<=3)
print("1>3 : ", 1>3)

3==3:  True
3!=1:  True
1==3:  False
1!=3:  True
1<3 :  True
3<3 :  False
3<=3:  True
1>3 :  False


In [ ]:
import numpy as np

a = np.array( [1,2,3,4,5] )
print("a = ", a)
print("a > 3 :", a > 3)

b = np.

-----------------
* Python IF...ELIF...ELSE Statement

In [16]:
a = 3
print("a = ",a)

if a == 3:
    print("(if -> ) a*2 = ", a*2)
else:
    print("(else -> ) a*3 = ", a*3)

a =  3
(if -> ) a*2 =  6


In [17]:
a = 5
print("a = ",a)

if a == 3:
    print("(if -> ) a*2 = ", a*2)
elif (a > 3) and (a <= 4):
    print("(elif -> ) a*3 = ", a*3)
else:
    print("(else -> ) a*4 = ", a*4)

a =  5
(else -> ) a*4 =  20
